### ISSUE TITLE
Integrate RSpec's error reporting with Vagrant's UI object

### ISSUE THREAD

**Issue by jvoorhis** [vvchik/vagrant-serverspec#3]

**Comment by elblivion** [comment]
Hi, first of all thanks for the plugin, I've been fiddling it and it's very useful!

I'd be interested in this feature. I was investigating and it looks like running RSpec might have to be converted to an `action_hook` so the `env[:ui]` object can be accessed. I might have a crack at doing this, I'm just wondering if you've already investigated and have a better idea of how this could be done.

Thanks,
Anthony

**Comment by vvchik** [comment]
Hi @elblivion it would be great if you can create PR with that feature.
this plugin is fully supported by community and you can take a part in that.
