### ISSUE TITLE
Cannot Install With Vagrant 1.9.2

### ISSUE THREAD

**Issue by tehmaspc** [vvchik/vagrant-serverspec#32]
Trying to install `vagrant-serverspec` with Vagrant 1.9.2 fails with following:

```
~ ➜ vagrant plugin list
vagrant-share (1.1.7, system)
~ ➜ vagrant plugin install vagrant-serverspec
Installing the 'vagrant-serverspec' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies nokogiri (~> 1.5.0) and nokogiri (= 1.6.7.1)
  Activated nokogiri-1.6.7.1
  which does not match conflicting dependency (~> 1.5.0)

  Conflicting dependency chains:
    vagrant-share (> 0), 1.1.7 activated, depends on
    vagrant (>= 1.9.2), 1.9.2 activated, depends on
    nokogiri (= 1.6.7.1), 1.6.7.1 activated

  versus:
    vagrant-serverspec (> 0), 1.1.1 activated, depends on
    winrm (>= 1.1.0, ~> 1.1), 1.1.0 activated, depends on
    nokogiri (~> 1.5.0)

```

System:
`MacOS X 10.12.3`

**Comment by tehmaspc** [comment]
I see the PR here: https://github.com/jvoorhis/vagrant-serverspec/pull/31

Tracking this issue here though - since this is blocking my team from upgrading to the latest Vagrant version.

Thanks.

**Comment by lmayorga1980** [comment]
Already sent a PR for that.

**Comment by vvchik** [comment]
Will check that PR this week

**Comment by lmayorga1980** [comment]
Sounds good.  If later i can own it then i can improve some of the open tickets and also add some testimg goodies.

**Comment by tehmaspc** [comment]
thanks guys!

**Comment by amatas** [comment]
Hi all, I'm also interested on the fixing of this issue. Any progress since 11 days ago? Thanks!

**Comment by lmayorga1980** [comment]
@tehmaspc @amatas @vvchik. Votes to move it to a different repository named serverspec2?

**Comment by jvoorhis** [comment]
Since @lmayorga1980 has raised the issue, I'd like to offer to transfer the repo, either to a new organization or a new maintainer if there is consensus around that. @vvchik may be a good choice since he already has the ability to push new releases to rubygems.org.

The simple truth is that I no longer use this project in any work or side projects, and my time has been too scarce to continue as maintainer.

**Comment by amatas** [comment]
I'm testing the changes made by @lmayorga1980 and they seem good to me.

**Comment by lmayorga1980** [comment]
I agree with @jvoorhis. If @vvchik can handle the changes then I am up for it.

**Comment by tehmaspc** [comment]
I concur w/ what @lmayorga1980 just stated.

**Comment by vvchik** [comment]
Ok, I can move it into my repo. Am I need just add new origin? Or GitHub have some possibility to do it?

**Comment by vvchik** [comment]
btw, PR is merged

**Comment by StefanScherer** [comment]
@vvchik Repos can be transferred to other users. Haven't done it in such a case, but you probably have to remove your fork first, then @jvoorhis transfers it to your github user and you can none of the watches and stars are lost.

https://help.github.com/articles/about-repository-transfers/
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

And thanks @jvoorhis to hand the repo over to a new maintainer.

**Comment by tal5ab** [comment]
On which version can we find this fix?

**Comment by lmayorga1980** [comment]
I believe it was merged but someone needs to upload the new built gem to rubygems.org. I guess you can build it yourself for the moment(master branch)

**Comment by vvchik** [comment]
will update it on rubygems soon :)

**Comment by lmayorga1980** [comment]
@vvchik should I have permissions to close issues?

**Comment by vvchik** [comment]
I can add you into collaborators team if you wish :)

**Comment by lmayorga1980** [comment]
sounds 👍

**Comment by vvchik** [comment]
Done

**Comment by lmayorga1980** [comment]
@vvchik making me a collaborator doesn't do it. Maybe a specific permission missing?

**Comment by vvchik** [comment]
@lmayorga1980, you are not accepted invite yet

**Comment by tehmaspc** [comment]
going to test 1.2 now that it's on rubygems.org

**Comment by tehmaspc** [comment]
it works! - remember to nuke the older version of `vagrant-serverspec` in order to get a clean install of 1.2. 

thanks all!

closing...

**Comment by StefanScherer** [comment]
Awesome, thanks!
