### ISSUE TITLE
How to pass parameters into server spec script?

### ISSUE THREAD

**Issue by avishnyakov** [vvchik/vagrant-serverspec#36]
Hey @vvchik, thanks for your amazing work. Been using this one for a while, total success.

Wonder if it's possible to pass parameters, args to server spe script? Someting like that:

```ruby
 vm_config.vm.provision :serverspec do |spec| 
          spec.pattern = [specs_file_path] 
          spec.args: args
        end
```

That way we would be able to parametrize specs. For instance, specifying which `yum` packafes to be installed in provisioning scripts and then passing the same varibale to the server spec script.

Coudn't find a way to get this done by looking into the source code of the pluging. May be there is a fast way to get this done?

**Comment by vvchik** [comment]
well this plugin should work pretty transparent for passing data to serverspec.
never tried but please check 'How to use Serverspec tests as shared behaviors' section in [official serverspec documentation ](http://serverspec.org/advanced_tips.html)
