### ISSUE TITLE
[feature] Support for `exclude-pattern`

### ISSUE THREAD

**Issue by endemics** [vvchik/vagrant-serverspec#44]
Hi,

I would like to be able to exclude patterns when running serverspec in Vagrant, as per [rspec exclude-pattern](https://relishapp.com/rspec/rspec-core/v/3-8/docs/configuration/exclude-pattern).

I am already doing that in my `Rakefile` (for when I am running outside of Vagrant), but it is currently not supported by `vagrant-serverspec`:

```
    RSpec::Core::RakeTask.new(t.to_s) do |task|
      task.pattern = "spec/#{role}/*_spec.rb"
      task.exclude_pattern = "spec/#{role}/provider_*_spec.rb"
    end
```

Would you be open to support this feature? If so I can try and give a go at making a PR.

Cheers,
Gildas

**Comment by vvchik** [comment]
Sure, go ahead!

**Comment by vvchik** [comment]
Hi, @endemics your PR merged, gem pushed. Closing.
